### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Nicoly",
    "email": "nicoly@gmail.com",
    "password": "abc123"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "nicoly@gmail.com",
    "password": "abc123"
}

### 3) Get users
GET http://localhost:3003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTk3ZTA2LWZkZjYtNGFhNS1iMTU2LWU2ZDQyOWE3ZGQ0YiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjAxNTEzMjgsImV4cCI6MTY2MDIzNzcyOH0.Yf2ltIia1fZDGd6MSik5RvbRTQcVsqpTL6eUgxDQ88U

### 3) Delete user
DELETE http://localhost:3003/users/b675fa97e06-fdf6-4aa5-b156-e6d429a7dd4b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTk3ZTA2LWZkZjYtNGFhNS1iMTU2LWU2ZDQyOWE3ZGQ0YiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjAxNTEzMjgsImV4cCI6MTY2MDIzNzcyOH0.Yf2ltIia1fZDGd6MSik5RvbRTQcVsqpTL6eUgxDQ88U

### 4) Edit user
PUT http://localhost:3003/users/f03017bb-2c08-4cdc-bb63-7fbd7cebe01f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTk3ZTA2LWZkZjYtNGFhNS1iMTU2LWU2ZDQyOWE3ZGQ0YiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjAxNTEzMjgsImV4cCI6MTY2MDIzNzcyOH0.Yf2ltIia1fZDGd6MSik5RvbRTQcVsqpTL6eUgxDQ88U
Content-Type: application/json

{
    "name": "Nicoly Barros"
}