### Endpoint de teste
GET http://localhost:3003/ping


### Endpoint signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Nicoly",
    "email": "nicoly@gmail.com",
    "password": "abc123"
}


### Endpoint login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "nicoly@gmail.com",
    "password": "abc123"
}


### Endpoint create show
POST http://localhost:3003/shows
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDc3OTg1NywiZXhwIjoxNjYwODY2MjU3fQ.iNsYIHbHMfYMdQUPDN3Fsvi0w-aFCkaCdLjISiI4VRo
Content-Type: application/json

{
    "band": "Nirvana",
    "startAt": "2022/12/09"
}


### Endpoint get shows
GET http://localhost:3003/shows


### Endpoint buy ticket
POST http://localhost:3003/shows/ticket/202
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1ODdkZGU4LWJkYTMtNDRkNC05MDY2LWQ2YWM5ZTI5MzZiNSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA4NTAwODIsImV4cCI6MTY2MDkzNjQ4Mn0.u-qfA2XdoEZdJoIm2hgnQBcEilk0qQq2TJ7BODs49tw


### Endpoint delete ticket
DELETE http://localhost:3003/shows/ticket/301
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0MGJmM2VhLTJlZGEtNDZjZC1hOGQwLWIyNjI3OGRlODcyMSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjA4MjQzNTEsImV4cCI6MTY2MDkxMDc1MX0.V_6lEva4ruJYWoumCUtQYOLR_7p0Zl5BV-d8aT6hfNM
